apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-single
    targetRevision: 0.10.0 #
    helm:
      values: |
        server:
          retentionPeriod: 14d
          persistentVolume:
            size: 10Gi
            storageClass: hcloud-volumes
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
