apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-applications
  namespace: argocd
spec:
  generators:
    - git:
        # POINT TO THE NEW WORKLOADS REPO
        repoURL: "https://github.com/kendricklawton/project-platform-workloads.git"
        revision: HEAD
        directories:
          - path: "*" # Now that it's a dedicated repo, path is just the root folders
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/kendricklawton/project-platform-workloads.git"
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
