version: "3"

dotenv: [".env"]

vars:
  PROJECT_NAME: "project-platform"
  ADMIN_IP: "{{.ADMIN_IP}}"

  # PACKER CONFIG
  PACKER_DIR: "infra/packer"

  # DigitalOcean
  DOCLOUD_IMAGE: "ubuntu-22-04-x64"
  DOCLOUD_K3S_DROPLET_TYPE: "s-4vcpu-8gb"
  DOCLOUD_TOKEN: "{{.DOCLOUD_TOKEN}}"

  # Hetzner
  HCLOUD_IMAGE: "ubuntu-22.04"
  HCLOUD_K3S_SERVER_TYPE: "cpx31"
  HCLOUD_LB_TYPE: "lb11"
  HCLOUD_TOKEN: "{{.HCLOUD_TOKEN}}"

  # COMPONENT VERSIONS
  K3S_VERSION: "v1.29.1+k3s2"
  GVISOR_VERSION: "latest"
  HETZNER_CCM_VERSION: "1.29.1"
  HETZNER_CSI_VERSION: "2.6.0"
  DIGITALOCEAN_CCM_VERSION: "0.1.58"
  DIGITALOCEAN_CSI_VERSION: "4.8.0"
  CILIUM_VERSION: "1.15.1"
  CNPG_VERSION: "1.28.1"
  INGRESS_NGINX_VERSION: "4.10.0"
  CERT_MANAGER_VERSION: "v1.14.0"
  NATS_VERSION: "2.10.12"
  KUBEARMOR_VERSION: "1.3.1"
  KYVERNO_VERSION: "3.2.6"
  FLUENT_BIT_VERSION: "3.0.0"
  VM_VERSION: "0.14.0"
  LOKI_VERSION: "5.43.3"
  GRAFANA_VERSION: "7.3.0"
  ARGOCD_VERSION: "6.7.11"
  KNATIVE_VERSION: "1.14.0"

  # Database Defaults
  DATABASE_URL: "{{.DATABASE_URL}}"

tasks:
  # PACKER WORKFLOWS
  _packer_build:
    internal: true
    silent: true
    desc: "Generic Packer Build Wrapper"
    env:
      PKR_VAR_hcloud_token: "{{.HCLOUD_TOKEN}}"
      PKR_VAR_docloud_token: "{{.DOCLOUD_TOKEN}}"
    cmds:
      - packer init {{.PACKER_DIR}}
      - >-
        packer build {{.BUILD_ARGS}}
        -var "hcloud_image={{.HCLOUD_IMAGE}}"
        -var "hcloud_k3s_server_type={{.HCLOUD_K3S_SERVER_TYPE}}"
        -var "docloud_image={{.DOCLOUD_IMAGE}}"
        -var "docloud_k3s_droplet_type={{.DOCLOUD_K3S_DROPLET_TYPE}}"
        -var "k3s_version={{.K3S_VERSION}}"
        -var "gvisor_version={{.GVISOR_VERSION}}"
        {{.PACKER_DIR}}/ubuntu.pkr.hcl

  packer:hz:
    desc: "Build Hetzner Images Only"
    cmds:
      - task: _packer_build
        vars: { BUILD_ARGS: "-only=*.hcloud.*" }

  packer:do:
    desc: "Build DigitalOcean Images Only"
    cmds:
      - task: _packer_build
        vars: { BUILD_ARGS: "-only=*.digitalocean.*" }

  packer:all:
    desc: "Build Both Hetzner and DigitalOcean Images"
    cmds:
      - task: _packer_build
        vars: { BUILD_ARGS: "" }

  # TERRAFORM CORE ENGINE
  _tf:
    internal: true
    dir: infra/terraform/providers/{{.PROVIDER}}
    vars:
      TFSTATE_BUCKET: "{{.PROJECT_NAME}}-tfstate-{{.CLOUD_ENV}}"
      CCM_VERSION: '{{if eq .PROVIDER "hetzner"}}{{.HETZNER_CCM_VERSION}}{{else}}{{.DIGITALOCEAN_CCM_VERSION}}{{end}}'
      CSI_VERSION: '{{if eq .PROVIDER "hetzner"}}{{.HETZNER_CSI_VERSION}}{{else}}{{.DIGITALOCEAN_CSI_VERSION}}{{end}}'
    env:
      GOOGLE_APPLICATION_CREDENTIALS: "{{.TASKFILE_DIR}}/keys/{{.PROJECT_NAME}}-tfstate-{{.CLOUD_ENV}}.json"
      DIGITALOCEAN_TOKEN: "{{.DOCLOUD_TOKEN}}"
      HCLOUD_TOKEN: "{{.HCLOUD_TOKEN}}"

      # TF_VAR Data
      # TF_VAR_hcloud_token: "{{.HCLOUD_TOKEN}}"
      # TF_VAR_docloud_token: "{{.DOCLOUD_TOKEN}}"
      TF_VAR_admin_ip: "{{.ADMIN_IP}}"
      TF_VAR_token: '{{if eq .PROVIDER "hetzner"}}{{.HCLOUD_TOKEN}}{{else}}{{.DOCLOUD_TOKEN}}{{end}}'
      TF_VAR_master_type: '{{if eq .PROVIDER "hetzner"}}{{.HCLOUD_K3S_SERVER_TYPE}}{{else}}{{.DOCLOUD_K3S_DROPLET_TYPE}}{{end}}'
      TF_VAR_worker_type: '{{if eq .PROVIDER "hetzner"}}{{.HCLOUD_K3S_SERVER_TYPE}}{{else}}{{.DOCLOUD_K3S_DROPLET_TYPE}}{{end}}'
      TF_VAR_load_balancer_type: '{{if eq .PROVIDER "hetzner"}}{{.HCLOUD_LB_TYPE}}{{else}}""{{end}}'
      TF_VAR_location: "{{.LOCATION}}"
      TF_VAR_project_name: "{{.PROJECT_NAME}}"
      TF_VAR_cloud_env: "{{.CLOUD_ENV}}"
      TF_VAR_ssh_key_name: '{{if eq .PROVIDER "hetzner"}}{{.HETZNER_SSH_KEY_NAME}}{{else}}{{.DIGITALOCEAN_SSH_KEY_NAME}}{{end}}'
      TF_VAR_letsencrypt_email: "{{.LETSENCRYPT_EMAIL}}"
      TF_VAR_tailscale_auth_k3s_server_key: "{{.TAILSCALE_AUTH_K3S_SERVER_KEY}}"
      TF_VAR_tailscale_auth_k3s_agent_key: "{{.TAILSCALE_AUTH_K3S_AGENT_KEY}}"
      TF_VAR_etcd_s3_bucket: "{{.PROJECT_NAME}}-etcd-{{.CLOUD_ENV}}"
      TF_VAR_registry_s3_bucket: "{{.PROJECT_NAME}}-registry-{{.CLOUD_ENV}}"
      TF_VAR_database_s3_bucket: "{{.PROJECT_NAME}}-database-{{.CLOUD_ENV}}"
      TF_VAR_logs_s3_bucket: "{{.PROJECT_NAME}}-logs-{{.CLOUD_ENV}}"

      # S3 Defaults
      TF_VAR_s3_region: "{{.S3_REGION}}"
      TF_VAR_s3_endpoint: "{{.S3_ENDPOINT}}"

      # Authentication
      TF_VAR_etcd_s3_access_key: "{{.ETCD_S3_ACCESS_KEY}}"
      TF_VAR_etcd_s3_secret_key: "{{.ETCD_S3_SECRET_KEY}}"
      TF_VAR_registry_s3_access_key: "{{.REGISTRY_S3_ACCESS_KEY}}"
      TF_VAR_registry_s3_secret_key: "{{.REGISTRY_S3_SECRET_KEY}}"
      TF_VAR_logs_s3_access_key: "{{.LOGS_S3_ACCESS_KEY}}"
      TF_VAR_logs_s3_secret_key: "{{.LOGS_S3_SECRET_KEY}}"
      TF_VAR_database_s3_access_key: "{{.DATABASE_S3_ACCESS_KEY}}"
      TF_VAR_database_s3_secret_key: "{{.DATABASE_S3_SECRET_KEY}}"
      TF_VAR_registry_htpasswd: "{{.REGISTRY_HTPASSWD}}"

      # Component Versions
      TF_VAR_ccm_version: "{{.CCM_VERSION}}"
      TF_VAR_csi_version: "{{.CSI_VERSION}}"
      TF_VAR_cilium_version: "{{.CILIUM_VERSION}}"
      TF_VAR_cnpg_version: "{{.CNPG_VERSION}}"
      TF_VAR_ingress_nginx_version: "{{.INGRESS_NGINX_VERSION}}"
      TF_VAR_cert_manager_version: "{{.CERT_MANAGER_VERSION}}"
      TF_VAR_nats_version: "{{.NATS_VERSION}}"
      TF_VAR_kubearmor_version: "{{.KUBEARMOR_VERSION}}"
      TF_VAR_kyverno_version: "{{.KYVERNO_VERSION}}"
      TF_VAR_fluent_bit_version: "{{.FLUENT_BIT_VERSION}}"
      TF_VAR_victoria_metrics_version: "{{.VM_VERSION}}"
      TF_VAR_loki_version: "{{.LOKI_VERSION}}"
      TF_VAR_grafana_version: "{{.GRAFANA_VERSION}}"
      TF_VAR_argocd_version: "{{.ARGOCD_VERSION}}"
      TF_VAR_knative_version: "{{.KNATIVE_VERSION}}"
    cmds:
      - echo "[TERRAFORM] {{.CMD}} -> {{.PROVIDER}} -> {{.LOCATION}} -> {{.CLOUD_ENV}}"
      # FIX: Updated prefix to match the CloudProvider/CloudEnv format
      - terraform init -reconfigure -backend-config="bucket={{.TFSTATE_BUCKET}}" -backend-config="prefix={{.PROVIDER}}"
      - terraform {{.CMD}} {{.ARGS}}

  # HETZNER INFRASTRUCTURE
  hz:plan:
    desc: "Plan Hetzner Ashburn (Dev)"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "hetzner"
          LOCATION: "ash"
          CLOUD_ENV: "dev"
          CMD: "plan"
          ARGS: "-out=tfplan"

  hz:apply:
    desc: "Apply Hetzner Ashburn (Dev)"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "hetzner"
          LOCATION: "ash"
          CLOUD_ENV: "dev"
          CMD: "apply"
          ARGS: "-auto-approve tfplan"

  hz:destroy:
    desc: "Destroy Hetzner Ashburn (Dev)"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "hetzner"
          LOCATION: "ash"
          CLOUD_ENV: "dev"
          CMD: "destroy"
          ARGS: "-auto-approve"

  hz:output:
    desc: "Show Hetzner Outputs"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "hetzner"
          LOCATION: "ash"
          CLOUD_ENV: "dev"
          CMD: "output"
          ARGS: ""

  hz:kubeconfig:
    desc: "Write Hetzner Kubeconfig to disk"
    cmds:
      - mkdir -p ~/.kube
      - terraform -chdir=infra/providers/hetzner output -raw kubeconfig > ~/.kube/config
      - chmod 600 ~/.kube/config
      - echo "✅ Kubeconfig successfully written to ~/.kube/config"

  # DIGITALOCEAN INFRASTRUCTURE
  do:plan:
    desc: "Plan DigitalOcean NYC3 (Dev)"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "digitalocean"
          LOCATION: "nyc3"
          CLOUD_ENV: "dev"
          CMD: "plan"
          ARGS: "-out=tfplan"

  do:apply:
    desc: "Apply DigitalOcean NYC3 (Dev)"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "digitalocean"
          LOCATION: "nyc3"
          CLOUD_ENV: "dev"
          CMD: "apply"
          ARGS: "-auto-approve tfplan"

  do:destroy:
    desc: "Destroy DigitalOcean NYC3 (Dev)"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "digitalocean"
          LOCATION: "nyc3"
          CLOUD_ENV: "dev"
          CMD: "destroy"
          ARGS: "-auto-approve"

  do:output:
    desc: "Show DigitalOcean Outputs"
    cmds:
      - task: _tf
        vars:
          PROVIDER: "digitalocean"
          LOCATION: "nyc3"
          CLOUD_ENV: "dev"
          CMD: "output"
          ARGS: ""

  # BUILD WORKFLOWS (Choice of ko or Docker)
  build:ko:api:
    desc: "Build the API container image using ko (Go-optimized)"
    dir: core
    env:
      KO_DOCKER_REPO: '{{.KO_DOCKER_REPO | default "ko.local"}}'
    cmds:
      - ko build ./cmd/platform-api --bare

  build:ko:cli:
    desc: "Build the CLI container image using ko (Go-optimized)"
    dir: core
    env:
      KO_DOCKER_REPO: '{{.KO_DOCKER_REPO | default "ko.local"}}'
    cmds:
      - ko build ./cmd/platform-cli --bare

  build:docker:api:
    desc: "Build the API container image using Docker"
    dir: core
    cmds:
      - docker build -t project-platform-api:latest --build-arg SERVICE_NAME=platform-api .

  build:docker:cli:
    desc: "Build the CLI container image using Docker"
    dir: core
    cmds:
      - docker build -t project-platform-cli:latest --build-arg SERVICE_NAME=platform-cli .

  # WEB APP WORKFLOWS
  web:dev:
    desc: "Show Web App"
    dir: web
    cmds:
      - npm run dev

  # DATABASE WORKFLOWS
  db:up:
    desc: "Start local PostgreSQL database"
    cmds:
      - docker compose up -d db

  db:down:
    desc: "Stop local PostgreSQL database"
    cmds:
      - docker compose down

  db:migrate:
    desc: "Run database migrations (up)"
    silent: true
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - migrate -path database/migrations -database "{{.DATABASE_URL}}" up

  db:migrate-down:
    desc: "Rollback the last database migration (down 1)"
    cmds:
      - migrate -path database/migrations -database "{{.DATABASE_URL}}" down 1

  db:create-migration:
    desc: "Create a new migration (usage: task db:create-migration NAME=create_users)"
    cmds:
      - migrate create -ext sql -dir database/migrations -seq {{.NAME}}
    requires:
      vars: [NAME]

  db:generate:
    desc: "Generate Go code from SQL using sqlc"
    dir: database
    cmds:
      - sqlc generate

  db:setup:
    desc: "Spin up DB, wait, migrate, and generate code"
    cmds:
      - task: db:up
      - echo "Waiting for DB to be ready..."
      - sleep 5
      - task: db:migrate
      - task: db:generate

  db:login:
    desc: "Login to the local PostgreSQL database"
    cmds:
      - docker exec -it project-platform-db-1 psql -U platform platform_db
