version: "3"

dotenv: [".env"]

vars:
  TF_DIR: "infra"
  PACKER_DIR: "packer"
  CLOUD_ENV: '{{.CLOUD_ENV | default "dev"}}'
  KUBECONFIG_PATH: ".kube/config"
  IMAGE_VERSION: '{{.IMAGE_VERSION | default "v1"}}'
  HCLOUD_LOCATION: '{{.HCLOUD_LOCATION | default "ash"}}'
  BUILD_SERVER_TYPE: '{{if eq .CLOUD_ENV "prod"}}cpx41{{else}}cpx21{{end}}'
  TF_CMD: >-
    export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/keys/gcp-tf-state-sa-{{.CLOUD_ENV}}.json" &&
    terraform -chdir={{.TF_DIR}}

  TF_VARS: >-
    -var="cloud_env={{.CLOUD_ENV}}"
    -var="image_version={{.IMAGE_VERSION}}"
    -var="gcp_project_id={{.GCP_PROJECT_ID}}"
    -var="project_name={{.PROJECT_NAME}}"
    -var="hcloud_token={{.HCLOUD_TOKEN}}"
    -var="ssh_key_name={{.SSH_KEY_NAME}}"
    -var="tailscale_auth_nat_key={{.TAILSCALE_AUTH_NAT_KEY}}"
    -var="tailscale_auth_server_key={{.TAILSCALE_AUTH_SERVER_KEY}}"
    -var="tailscale_auth_agent_key={{.TAILSCALE_AUTH_AGENT_KEY}}"

tasks:
  _tf_init:
    internal: true
    cmds:
      - echo "🔧 Initializing {{.CLOUD_ENV}} state..."
      - "{{.TF_CMD}} init -reconfigure -backend-config='bucket={{.PROJECT_NAME}}-tf-state-{{.CLOUD_ENV}}'"

  packer:build:
    desc: "Build Golden Images for all regions"
    cmds:
      - packer init {{.PACKER_DIR}}
      - >-
        packer build
        -var "hcloud_token={{.HCLOUD_TOKEN}}"
        -var "server_type={{.BUILD_SERVER_TYPE}}"
        {{.PACKER_DIR}}/ubuntu-k3s.pkr.hcl

  infra:plan:
    desc: "Generate and show Terraform Plan"
    deps: [_tf_init]
    cmds:
      - |
        ENV_UPPER=$(echo "{{.CLOUD_ENV}}" | tr '[:lower:]' '[:upper:]')
        BUCKET=$(eval echo \$ETCD_S3_BUCKET_${ENV_UPPER})
        ACCESS=$(eval echo \$ETCD_S3_ACCESS_KEY_${ENV_UPPER})
        SECRET=$(eval echo \$ETCD_S3_SECRET_KEY_${ENV_UPPER})

        {{.TF_CMD}} plan {{.TF_VARS}} \
          -var="etcd_s3_bucket=${BUCKET}" \
          -var="etcd_s3_access_key=${ACCESS}" \
          -var="etcd_s3_secret_key=${SECRET}"
    # Removed sources to ensure plan always runs even if only .env changed

  infra:apply:
    desc: "Apply changes to infrastructure"
    prompt: "⚠️  Applying to {{.CLOUD_ENV}} ({{.HCLOUD_LOCATION}}). Proceed?"
    deps: [_tf_init]
    cmds:
      - |
        ENV_UPPER=$(echo "{{.CLOUD_ENV}}" | tr '[:lower:]' '[:upper:]')
        BUCKET=$(eval echo \$ETCD_S3_BUCKET_${ENV_UPPER})
        ACCESS=$(eval echo \$ETCD_S3_ACCESS_KEY_${ENV_UPPER})
        SECRET=$(eval echo \$ETCD_S3_SECRET_KEY_${ENV_UPPER})

        {{.TF_CMD}} apply -auto-approve {{.TF_VARS}} \
          -var="etcd_s3_bucket=${BUCKET}" \
          -var="etcd_s3_access_key=${ACCESS}" \
          -var="etcd_s3_secret_key=${SECRET}"

  infra:kubeconfig:
    desc: "Fetch Kubeconfig from leader via Tailscale MagicDNS"
    vars:
      MASTER: "{{.CLOUD_ENV}}-{{.PROJECT_NAME}}-server-0"
    cmds:
      - mkdir -p .kube
      - echo "⏳ Checking connection to {{.MASTER}}..."
      - until nc -zvw5 {{.MASTER}} 22; do sleep 5; done
      - scp -o StrictHostKeyChecking=no -o ConnectTimeout=5 root@{{.MASTER}}:/etc/rancher/k3s/k3s.yaml {{.KUBECONFIG_PATH}}
      - sed -i.bak "s/127.0.0.1/{{.MASTER}}/g" {{.KUBECONFIG_PATH}} && rm -f {{.KUBECONFIG_PATH}}.bak
      - chmod 600 {{.KUBECONFIG_PATH}}
      - echo "✅ Kubeconfig secured for {{.MASTER}}"

  infra:deploy:
    desc: "Full Pipeline: Plan -> Apply -> Config"
    cmds:
      - task: infra:plan
      - task: infra:apply
      - task: infra:kubeconfig

  infra:destroy:
    desc: "Nuke infrastructure for specific environment"
    prompt: "❌ DESTROY {{.CLOUD_ENV}}? This cannot be undone."
    deps: [_tf_init]
    cmds:
      - |
        ENV_UPPER=$(echo "{{.CLOUD_ENV}}" | tr '[:lower:]' '[:upper:]')
        BUCKET=$(eval echo \$ETCD_S3_BUCKET_${ENV_UPPER})
        ACCESS=$(eval echo \$ETCD_S3_ACCESS_KEY_${ENV_UPPER})
        SECRET=$(eval echo \$ETCD_S3_SECRET_KEY_${ENV_UPPER})

        {{.TF_CMD}} destroy -auto-approve {{.TF_VARS}} \
          -var="etcd_s3_bucket=${BUCKET}" \
          -var="etcd_s3_access_key=${ACCESS}" \
          -var="etcd_s3_secret_key=${SECRET}"
      - rm -f {{.KUBECONFIG_PATH}}

  ssh:prep:
    desc: "Prepare SSH agent and clear old lab keys"
    cmds:
      - ssh-add -D
      - ssh-add ~/.ssh/
      - ssh-keygen -R 178.156.199.192 # Clear the NAT's old public IP
      - echo "✅ SSH Agent ready with lab keys"
