#  INFRASTRUCTURE TASKFILE
version: "3"

dotenv: [".env"]

vars:
  #  GLOBAL CONFIGURATION
  TF_DIR: "infra"
  PACKER_DIR: "packer"
  CLOUD_ENV: '{{.CLOUD_ENV | default "dev"}}'
  KEY_NAME: "{{.KEY_NAME}}"
  KUBECONFIG_PATH: "kube/config"
  HCLOUD_LOCATION: '{{.HCLOUD_LOCATION | default "ash"}}'
  LETSENCRYPT_EMAIL: "{{.LETSENCRYPT_EMAIL}}"

  #  BUILD STRATEGY (Hetzner)
  K3S_SERVER_TYPE: "cpx21"
  NAT_SERVER_TYPE: "cpx11"
  IMAGE: "{{.IMAGE}}"

  # VERSION PINNING & MEMORY BUDGET
  # Base Infrastructure
  # K3s combines API/Etcd/Controller into one binary.
  # - Server Node: ~800MB - 1GB (Depending on load)
  # - Agent Node:  ~300MB - 400MB (Idle)
  K3S_VERSION: "v1.29.1+k3s2"

  # Helm is just a CLI tool used during build/deploy.
  # - Runtime RAM: 0MB (It does not run as a service on the cluster)
  HELM_VERSION: "v3.14.2"

  # Core Networking & Storage
  HCLOUD_CCM_VERSION: "1.29.1" # ~50MB (Connects K3s to Hetzner API)
  HCLOUD_CSI_VERSION: "2.6.0" # ~50MB (Mounts Volumes)
  CILIUM_VERSION: "1.15.1" # ~300MB (Critical: eBPF Firewall/Networking)
  INGRESS_NGINX_VERSION: "4.10.0" # ~200MB (The entry door for all traffic)
  CERT_MANAGER_VERSION: "v1.14.0" # ~120MB (Auto-renews SSL Certs)
  NATS_VERSION: "1.2.4" # ~150MB (Messaging/Queue for Platform)

  # 🚀 THE "SKINNY BOY" STACK (Security & Observability)
  # Total Additional RAM: ~800MB (vs ~2.5GB for the "Chunky" stack)
  KUBEARMOR_VERSION: "1.3.1" # ~100MB (Enforcement vs Falco's 800MB)
  FLUENT_BIT_VERSION: "0.44.0" # ~80MB  (Log Shipping agent)
  VM_VERSION: "0.14.0" # ~250MB (VictoriaMetrics: Metrics DB)
  LOKI_VERSION: "5.43.3" # ~300MB (Loki: Log DB)
  GRAFANA_VERSION: "7.3.0" # ~80MB  (Visual Dashboard)

  # TERRAFORM WRAPPERS
  TF_CMD: >-
    export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/keys/{{.KEY_NAME}}-{{.CLOUD_ENV}}.json" &&
    terraform -chdir={{.TF_DIR}}

  TF_VARS: >-
    -var="cloud_env={{.CLOUD_ENV}}"
    -var="hcloud_location={{.HCLOUD_LOCATION}}"
    -var="gcp_project_id={{.GCP_PROJECT_ID}}"
    -var="project_name={{.PROJECT_NAME}}"
    -var="hcloud_token={{.HCLOUD_TOKEN}}"
    -var="ssh_key_name={{.SSH_KEY_NAME}}"
    -var="tailscale_auth_nat_key={{.TAILSCALE_AUTH_NAT_KEY}}"
    -var="tailscale_auth_k3s_server_key={{.TAILSCALE_AUTH_K3S_SERVER_KEY}}"
    -var="tailscale_auth_k3s_agent_key={{.TAILSCALE_AUTH_K3S_AGENT_KEY}}"
    -var="letsencrypt_email={{.LETSENCRYPT_EMAIL}}"
    -var="hcloud_ccm_version={{.HCLOUD_CCM_VERSION}}"
    -var="hcloud_csi_version={{.HCLOUD_CSI_VERSION}}"
    -var="cilium_version={{.CILIUM_VERSION}}"
    -var="ingress_nginx_version={{.INGRESS_NGINX_VERSION}}"
    -var="cert_manager_version={{.CERT_MANAGER_VERSION}}"
    -var="nats_version={{.NATS_VERSION}}"
    -var="kubearmor_version={{.KUBEARMOR_VERSION}}"
    -var="fluent_bit_version={{.FLUENT_BIT_VERSION}}"
    -var="registry_htpasswd={{.REGISTRY_HTPASSWD}}"
    -var="vm_version={{.VM_VERSION}}"
    -var="loki_version={{.LOKI_VERSION}}"
    -var="grafana_version={{.GRAFANA_VERSION}}"

tasks:
  _tf_init:
    internal: true
    desc: "Helper: Initialize Terraform Backend"
    cmds:
      - echo "🔧 Initializing {{.CLOUD_ENV}} state..."
      - "{{.TF_CMD}} init -reconfigure -backend-config='bucket={{.PROJECT_NAME}}-tf-state-{{.CLOUD_ENV}}'"

  packer:build:
    desc: "Build Golden Image (Ubuntu + K3s + Helm)"
    cmds:
      - packer init {{.PACKER_DIR}}
      - >-
        packer build
        -var "hcloud_token={{.HCLOUD_TOKEN}}"
        -var "nat_server_type={{.NAT_SERVER_TYPE}}"
        -var "k3s_server_type={{.K3S_SERVER_TYPE}}"
        -var "k3s_version={{.K3S_VERSION}}"
        -var "helm_version={{.HELM_VERSION}}"
        -var "image={{.IMAGE}}"
        {{.PACKER_DIR}}/ubuntu.pkr.hcl

  infra:plan:
    desc: "Terraform Plan"
    deps: [_tf_init]
    cmds:
      - |
        ENV_UPPER=$(echo "{{.CLOUD_ENV}}" | tr '[:lower:]' '[:upper:]')
        ETCD_BUCKET=$(eval echo \$ETCD_S3_BUCKET_${ENV_UPPER})
        ETCD_ACCESS=$(eval echo \$ETCD_S3_ACCESS_KEY_${ENV_UPPER})
        ETCD_SECRET=$(eval echo \$ETCD_S3_SECRET_KEY_${ENV_UPPER})
        REGISTRY_BUCKET=$(eval echo \$REGISTRY_S3_BUCKET_${ENV_UPPER})
        REGISTRY_ACCESS=$(eval echo \$REGISTRY_S3_ACCESS_KEY_${ENV_UPPER})
        REGISTRY_SECRET=$(eval echo \$REGISTRY_S3_SECRET_KEY_${ENV_UPPER})
        LOGS_BUCKET=$(eval echo \$LOGS_S3_BUCKET_${ENV_UPPER})
        LOGS_ACCESS=$(eval echo \$LOGS_S3_ACCESS_KEY_${ENV_UPPER})
        LOGS_SECRET=$(eval echo \$LOGS_S3_SECRET_KEY_${ENV_UPPER})

        {{.TF_CMD}} plan {{.TF_VARS}} \
          -var="etcd_s3_bucket=${ETCD_BUCKET}" \
          -var="etcd_s3_access_key=${ETCD_ACCESS}" \
          -var="etcd_s3_secret_key=${ETCD_SECRET}" \
          -var="registry_s3_bucket=${REGISTRY_BUCKET}" \
          -var="registry_s3_access_key=${REGISTRY_ACCESS}" \
          -var="registry_s3_secret_key=${REGISTRY_SECRET}" \
          -var="logs_s3_bucket=${LOGS_BUCKET}" \
          -var="logs_s3_access_key=${LOGS_ACCESS}" \
          -var="logs_s3_secret_key=${LOGS_SECRET}"

  infra:apply:
    desc: "Terraform Apply"
    prompt: "⚠️  Applying to {{.CLOUD_ENV}} ({{.HCLOUD_LOCATION}}). Proceed?"
    deps: [_tf_init]
    cmds:
      - |
        ENV_UPPER=$(echo "{{.CLOUD_ENV}}" | tr '[:lower:]' '[:upper:]')
        ETCD_BUCKET=$(eval echo \$ETCD_S3_BUCKET_${ENV_UPPER})
        ETCD_ACCESS=$(eval echo \$ETCD_S3_ACCESS_KEY_${ENV_UPPER})
        ETCD_SECRET=$(eval echo \$ETCD_S3_SECRET_KEY_${ENV_UPPER})
        REGISTRY_BUCKET=$(eval echo \$REGISTRY_S3_BUCKET_${ENV_UPPER})
        REGISTRY_ACCESS=$(eval echo \$REGISTRY_S3_ACCESS_KEY_${ENV_UPPER})
        REGISTRY_SECRET=$(eval echo \$REGISTRY_S3_SECRET_KEY_${ENV_UPPER})
        LOGS_BUCKET=$(eval echo \$LOGS_S3_BUCKET_${ENV_UPPER})
        LOGS_ACCESS=$(eval echo \$LOGS_S3_ACCESS_KEY_${ENV_UPPER})
        LOGS_SECRET=$(eval echo \$LOGS_S3_SECRET_KEY_${ENV_UPPER})

        {{.TF_CMD}} apply -auto-approve {{.TF_VARS}} \
          -var="etcd_s3_bucket=${ETCD_BUCKET}" \
          -var="etcd_s3_access_key=${ETCD_ACCESS}" \
          -var="etcd_s3_secret_key=${ETCD_SECRET}" \
          -var="registry_s3_bucket=${REGISTRY_BUCKET}" \
          -var="registry_s3_access_key=${REGISTRY_ACCESS}" \
          -var="registry_s3_secret_key=${REGISTRY_SECRET}" \
          -var="logs_s3_bucket=${LOGS_BUCKET}" \
          -var="logs_s3_access_key=${LOGS_ACCESS}" \
          -var="logs_s3_secret_key=${LOGS_SECRET}"

  infra:kubeconfig:
    desc: "Fetch Kubeconfig via Tailscale"
    vars:
      DNS_NAME: "{{.CLOUD_ENV}}-{{.PROJECT_NAME}}-server-01"
      SSH_TARGET: "{{.DNS_NAME}}"
    cmds:
      - mkdir -p .kube
      - until ssh -q {{.SSH_TARGET}} exit; do sleep 5; done
      - scp {{.SSH_TARGET}}:/etc/rancher/k3s/k3s.yaml {{.KUBECONFIG_PATH}}
      - sed -i.bak "s/127.0.0.1/{{.DNS_NAME}}/g" {{.KUBECONFIG_PATH}} && rm -f {{.KUBECONFIG_PATH}}.bak
      - chmod 600 {{.KUBECONFIG_PATH}}
      - echo "✅ Kubeconfig secured."

  infra:deploy:
    desc: "Full Pipeline: Plan -> Apply -> Kubeconfig"
    cmds:
      - task: infra:plan
      - task: infra:apply
      - task: infra:kubeconfig

  infra:destroy:
    desc: "TEARDOWN"
    prompt: "❌ DESTROY {{.CLOUD_ENV}}? This cannot be undone."
    deps: [_tf_init]
    cmds:
      - |
        ENV_UPPER=$(echo "{{.CLOUD_ENV}}" | tr '[:lower:]' '[:upper:]')
        ETCD_BUCKET=$(eval echo \$ETCD_S3_BUCKET_${ENV_UPPER})
        ETCD_ACCESS=$(eval echo \$ETCD_S3_ACCESS_KEY_${ENV_UPPER})
        ETCD_SECRET=$(eval echo \$ETCD_S3_SECRET_KEY_${ENV_UPPER})
        REGISTRY_BUCKET=$(eval echo \$REGISTRY_S3_BUCKET_${ENV_UPPER})
        REGISTRY_ACCESS=$(eval echo \$REGISTRY_S3_ACCESS_KEY_${ENV_UPPER})
        REGISTRY_SECRET=$(eval echo \$REGISTRY_S3_SECRET_KEY_${ENV_UPPER})
        LOGS_BUCKET=$(eval echo \$LOGS_S3_BUCKET_${ENV_UPPER})
        LOGS_ACCESS=$(eval echo \$LOGS_S3_ACCESS_KEY_${ENV_UPPER})
        LOGS_SECRET=$(eval echo \$LOGS_S3_SECRET_KEY_${ENV_UPPER})

        {{.TF_CMD}} destroy -auto-approve {{.TF_VARS}} \
          -var="etcd_s3_bucket=${ETCD_BUCKET}" \
          -var="etcd_s3_access_key=${ETCD_ACCESS}" \
          -var="etcd_s3_secret_key=${ETCD_SECRET}" \
          -var="registry_s3_bucket=${REGISTRY_BUCKET}" \
          -var="registry_s3_access_key=${REGISTRY_ACCESS}" \
          -var="registry_s3_secret_key=${REGISTRY_SECRET}" \
          -var="logs_s3_bucket=${LOGS_BUCKET}" \
          -var="logs_s3_access_key=${LOGS_ACCESS}" \
          -var="logs_s3_secret_key=${LOGS_SECRET}"
      - rm -f {{.KUBECONFIG_PATH}}

  dev:web:
    desc: "Start local web development server"
    dir: web
    cmds:
      - npm run dev
