# TENANT & PLATFORM WORKLOADS
# Primary Tenant Namespace (For user-deployed Go/Rust/Zig APIs)
# Matches your gVisor enforcement policy
apiVersion: v1
kind: Namespace
metadata:
  name: project-platform
  labels:
    platform.io/managed-by: argocd
    # Native Kubernetes security: Block privileged pods and host mounts
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted

---
# Core Platform Backend (Internal Registry, CNPG Databases)
apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    platform.io/managed-by: argocd
    pod-security.kubernetes.io/enforce: baseline


# OBSERVABILITY & SECURITY METADATA
---
# Logging and Metrics (Loki, Fluent Bit, VictoriaMetrics, Grafana)
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    platform.io/managed-by: argocd
    # PSA is omitted here because Fluent Bit requires hostPath mounts to read /var/log

---
# Admission Controller (Kyverno)
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    platform.io/managed-by: argocd

---
# eBPF Runtime Security (KubeArmor)
apiVersion: v1
kind: Namespace
metadata:
  name: kubearmor
  labels:
    platform.io/managed-by: argocd


# SERVERLESS & EVENTING
---
# Knative Serving (Scale-to-zero compute engine)
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    platform.io/managed-by: argocd

---
# Knative Eventing
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    platform.io/managed-by: argocd

---
# Eventing Backbone (NATS JetStream)
apiVersion: v1
kind: Namespace
metadata:
  name: nats
  labels:
    platform.io/managed-by: argocd


# OPERATORS & BUILD ENGINES
---
# PostgreSQL Database Operator
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    platform.io/managed-by: argocd

---
# Polyglot Build Engine (kpack)
apiVersion: v1
kind: Namespace
metadata:
  name: kpack
  labels:
    platform.io/managed-by: argocd
    # kpack is designed to build containers securely without root
    pod-security.kubernetes.io/enforce: baseline
