apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubearmor
  namespace: argocd
  labels:
    platform.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://kubearmor.github.io/charts"
    chart: kubearmor-operator
    targetRevision: 1.3.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubearmor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
