// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ============================================================================
	// DOMAINS
	// ============================================================================
	AddDomain(ctx context.Context, arg AddDomainParams) (Domain, error)
	// ============================================================================
	// WORKSPACE MEMBERS
	// ============================================================================
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	CancelDeployment(ctx context.Context, arg CancelDeploymentParams) (Deployment, error)
	CountQueuedDeployments(ctx context.Context) (int64, error)
	CountWorkspaceQueuedDeployments(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// ============================================================================
	// AUDIT LOG
	// ============================================================================
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error
	// ============================================================================
	// DEPLOYMENTS
	// ============================================================================
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	// ============================================================================
	// PROJECTS
	// ============================================================================
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// ============================================================================
	// QUERIES: sqlc query definitions
	// Naming: sqlc conventions (:one, :many, :exec, :execrows, :copyfrom)
	// Auth pattern: WHERE EXISTS subquery for RBAC inline with mutations
	// ============================================================================
	// ============================================================================
	// USERS
	// ============================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ============================================================================
	// WEBHOOKS
	// ============================================================================
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	// ============================================================================
	// WORKSPACES
	// ============================================================================
	// Atomic CTE: Creates a workspace and immediately assigns the creator as the owner.
	// Bypasses the chicken-and-egg RBAC problem natively in Postgres.
	CreateWorkspaceWithOwner(ctx context.Context, arg CreateWorkspaceWithOwnerParams) (CreateWorkspaceWithOwnerRow, error)
	DeleteDomain(ctx context.Context, arg DeleteDomainParams) (int64, error)
	DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) (int64, error)
	DeleteOrphanedWorkspaces(ctx context.Context, userID uuid.UUID) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error)
	GetBuildLogCount(ctx context.Context, deploymentID uuid.UUID) (int64, error)
	GetBuildLogs(ctx context.Context, arg GetBuildLogsParams) ([]GetBuildLogsRow, error)
	GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error)
	GetDomainByName(ctx context.Context, domain string) (GetDomainByNameRow, error)
	GetEnvVarsForDeployment(ctx context.Context, arg GetEnvVarsForDeploymentParams) ([]GetEnvVarsForDeploymentRow, error)
	GetLatestDeployment(ctx context.Context, arg GetLatestDeploymentParams) (Deployment, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetStaleBuilds(ctx context.Context) ([]Deployment, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWebhookByProviderInstall(ctx context.Context, arg GetWebhookByProviderInstallParams) (GetWebhookByProviderInstallRow, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error)
	GetWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]GetWorkspacesForUserRow, error)
	InsertBuildLogBatch(ctx context.Context, arg []InsertBuildLogBatchParams) (int64, error)
	// ============================================================================
	// BUILD LOG LINES
	// ============================================================================
	InsertBuildLogLine(ctx context.Context, arg InsertBuildLogLineParams) error
	ListEnvVarKeys(ctx context.Context, arg ListEnvVarKeysParams) ([]ListEnvVarKeysRow, error)
	ListProjectDeployments(ctx context.Context, arg ListProjectDeploymentsParams) ([]Deployment, error)
	ListProjectDomains(ctx context.Context, arg ListProjectDomainsParams) ([]Domain, error)
	ListProjectWebhooks(ctx context.Context, arg ListProjectWebhooksParams) ([]Webhook, error)
	ListResourceAuditLog(ctx context.Context, arg ListResourceAuditLogParams) ([]ListResourceAuditLogRow, error)
	ListWorkspaceAuditLog(ctx context.Context, arg ListWorkspaceAuditLogParams) ([]ListWorkspaceAuditLogRow, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspaceProjects(ctx context.Context, arg ListWorkspaceProjectsParams) ([]Project, error)
	// ============================================================================
	// ONBOARDING
	// ============================================================================
	// Atomic: creates user + personal workspace + owner membership in one transaction
	OnboardUserWithWorkspace(ctx context.Context, arg OnboardUserWithWorkspaceParams) (uuid.UUID, error)
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (int64, error)
	SoftDeleteDeployment(ctx context.Context, arg SoftDeleteDeploymentParams) (int64, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error)
	UpdateDomainTLSStatus(ctx context.Context, arg UpdateDomainTLSStatusParams) (Domain, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (int64, error)
	// ============================================================================
	// SECRETS MANAGEMENT
	// ============================================================================
	UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) (ProjectEnvVar, error)
	VerifyDomain(ctx context.Context, id uuid.UUID) (Domain, error)
}

var _ Querier = (*Queries)(nil)
