// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ============================================================================
	// DOMAINS
	// ============================================================================
	AddDomain(ctx context.Context, arg AddDomainParams) (Domain, error)
	// ============================================================================
	// TEAM MEMBERS
	// ============================================================================
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	CancelDeployment(ctx context.Context, arg CancelDeploymentParams) (Deployment, error)
	CountQueuedDeployments(ctx context.Context) (int64, error)
	CountTeamQueuedDeployments(ctx context.Context, teamID uuid.UUID) (int64, error)
	// ============================================================================
	// AUDIT LOG
	// ============================================================================
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error
	// ============================================================================
	// DEPLOYMENTS
	// ============================================================================
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	// ============================================================================
	// PROJECTS
	// ============================================================================
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// ============================================================================
	// TEAMS
	// ============================================================================
	// Atomic CTE: Creates a team and immediately assigns the creator as the owner.
	// Bypasses the chicken-and-egg RBAC problem natively in Postgres.
	CreateTeamWithOwner(ctx context.Context, arg CreateTeamWithOwnerParams) (CreateTeamWithOwnerRow, error)
	// ============================================================================
	// QUERIES: sqlc query definitions
	// Naming: sqlc conventions (:one, :many, :exec, :execrows, :copyfrom)
	// Auth pattern: WHERE EXISTS subquery for RBAC inline with mutations
	// ============================================================================
	// ============================================================================
	// USERS
	// ============================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ============================================================================
	// WEBHOOKS
	// ============================================================================
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	DeleteDomain(ctx context.Context, arg DeleteDomainParams) (int64, error)
	DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) (int64, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error)
	GetBuildLogCount(ctx context.Context, deploymentID uuid.UUID) (int64, error)
	GetBuildLogs(ctx context.Context, arg GetBuildLogsParams) ([]GetBuildLogsRow, error)
	GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error)
	GetDomainByName(ctx context.Context, domain string) (GetDomainByNameRow, error)
	GetEnvVarsForDeployment(ctx context.Context, arg GetEnvVarsForDeploymentParams) ([]GetEnvVarsForDeploymentRow, error)
	GetLatestDeployment(ctx context.Context, arg GetLatestDeploymentParams) (Deployment, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetStaleBuilds(ctx context.Context) ([]Deployment, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, slug string) (Team, error)
	GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (GetTeamMemberRow, error)
	GetTeamUsageDetail(ctx context.Context, arg GetTeamUsageDetailParams) ([]UsageRecord, error)
	GetTeamUsageSummary(ctx context.Context, arg GetTeamUsageSummaryParams) ([]GetTeamUsageSummaryRow, error)
	GetTeamsForUser(ctx context.Context, userID uuid.UUID) ([]GetTeamsForUserRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWebhookByProviderInstall(ctx context.Context, arg GetWebhookByProviderInstallParams) (GetWebhookByProviderInstallRow, error)
	InsertBuildLogBatch(ctx context.Context, arg []InsertBuildLogBatchParams) (int64, error)
	// ============================================================================
	// BUILD LOG LINES
	// ============================================================================
	InsertBuildLogLine(ctx context.Context, arg InsertBuildLogLineParams) error
	ListEnvVarKeys(ctx context.Context, arg ListEnvVarKeysParams) ([]ListEnvVarKeysRow, error)
	ListProjectDeployments(ctx context.Context, arg ListProjectDeploymentsParams) ([]Deployment, error)
	ListProjectDomains(ctx context.Context, arg ListProjectDomainsParams) ([]Domain, error)
	ListProjectWebhooks(ctx context.Context, arg ListProjectWebhooksParams) ([]Webhook, error)
	ListResourceAuditLog(ctx context.Context, arg ListResourceAuditLogParams) ([]ListResourceAuditLogRow, error)
	ListTeamAuditLog(ctx context.Context, arg ListTeamAuditLogParams) ([]ListTeamAuditLogRow, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeamProjects(ctx context.Context, arg ListTeamProjectsParams) ([]Project, error)
	// ============================================================================
	// ONBOARDING
	// ============================================================================
	// Atomic: creates user + personal team + owner membership in one transaction
	OnboardUserWithTeam(ctx context.Context, arg OnboardUserWithTeamParams) (uuid.UUID, error)
	// ============================================================================
	// USAGE / BILLING
	// ============================================================================
	RecordUsage(ctx context.Context, arg RecordUsageParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error)
	SoftDeleteDeployment(ctx context.Context, arg SoftDeleteDeploymentParams) (int64, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error)
	UpdateDomainTLSStatus(ctx context.Context, arg UpdateDomainTLSStatusParams) (Domain, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserStripeCustomerID(ctx context.Context, arg UpdateUserStripeCustomerIDParams) (User, error)
	UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) (User, error)
	// ============================================================================
	// SECRETS MANAGEMENT
	// ============================================================================
	UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) (ProjectEnvVar, error)
	VerifyDomain(ctx context.Context, id uuid.UUID) (Domain, error)
}

var _ Querier = (*Queries)(nil)
