// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (
    id, project_id, user_id, role
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, project_id, user_id, role, created_at
`

type AddProjectMemberParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRowContext(ctx, addProjectMember,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const checkUserProjectAccess = `-- name: CheckUserProjectAccess :one
SELECT role FROM project_members
WHERE project_id = $1 AND user_id = $2 LIMIT 1
`

type CheckUserProjectAccessParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// Fast RBAC check to ensure a user is allowed to deploy to a project
func (q *Queries) CheckUserProjectAccess(ctx context.Context, arg CheckUserProjectAccessParams) (string, error) {
	row := q.db.QueryRowContext(ctx, checkUserProjectAccess, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const createDeployment = `-- name: CreateDeployment :one

INSERT INTO deployments (
    id, project_id, image, replicas, status, url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, project_id, image, replicas, status, url, created_at, updated_at
`

type CreateDeploymentParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Image     string    `json:"image"`
	Replicas  int32     `json:"replicas"`
	Status    string    `json:"status"`
	Url       string    `json:"url"`
}

// DEPLOYMENTS
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.ProjectID,
		arg.Image,
		arg.Replicas,
		arg.Status,
		arg.Url,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Image,
		&i.Replicas,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id, name, region
) VALUES (
    $1, $2, $3
)
RETURNING id, name, region, created_at, updated_at
`

type CreateProjectParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Region string    `json:"region"`
}

// PROJECTS & RBAC
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ID, arg.Name, arg.Region)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    id, email, name, stripe_customer_id, tier
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, email, name, stripe_customer_id, tier, created_at, updated_at
`

type CreateUserParams struct {
	ID               uuid.UUID      `json:"id"`
	Email            string         `json:"email"`
	Name             string         `json:"name"`
	StripeCustomerID sql.NullString `json:"stripe_customer_id"`
	Tier             string         `json:"tier"`
}

// USERS
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.StripeCustomerID,
		arg.Tier,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.StripeCustomerID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, project_id, image, replicas, status, url, created_at, updated_at FROM deployments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeployment(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Image,
		&i.Replicas,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextQueuedDeployment = `-- name: GetNextQueuedDeployment :one
SELECT id, project_id, image, replicas, status, url, created_at, updated_at FROM deployments
WHERE status = 'queued'
ORDER BY id ASC
LIMIT 1
`

// Used by the background worker to grab the next job
func (q *Queries) GetNextQueuedDeployment(ctx context.Context) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getNextQueuedDeployment)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Image,
		&i.Replicas,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, region, created_at, updated_at FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectUsage = `-- name: GetProjectUsage :one
SELECT id, project_id, billing_period, compute_seconds, bandwidth_bytes, created_at, updated_at FROM project_usage
WHERE project_id = $1 AND billing_period = $2 LIMIT 1
`

type GetProjectUsageParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	BillingPeriod string    `json:"billing_period"`
}

func (q *Queries) GetProjectUsage(ctx context.Context, arg GetProjectUsageParams) (ProjectUsage, error) {
	row := q.db.QueryRowContext(ctx, getProjectUsage, arg.ProjectID, arg.BillingPeriod)
	var i ProjectUsage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BillingPeriod,
		&i.ComputeSeconds,
		&i.BandwidthBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, stripe_customer_id, tier, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.StripeCustomerID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, stripe_customer_id, tier, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.StripeCustomerID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementProjectUsage = `-- name: IncrementProjectUsage :one

INSERT INTO project_usage (
    id, project_id, billing_period, compute_seconds, bandwidth_bytes
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (project_id, billing_period)
DO UPDATE SET
    compute_seconds = project_usage.compute_seconds + EXCLUDED.compute_seconds,
    bandwidth_bytes = project_usage.bandwidth_bytes + EXCLUDED.bandwidth_bytes,
    updated_at = NOW()
RETURNING id, project_id, billing_period, compute_seconds, bandwidth_bytes, created_at, updated_at
`

type IncrementProjectUsageParams struct {
	ID             uuid.UUID `json:"id"`
	ProjectID      uuid.UUID `json:"project_id"`
	BillingPeriod  string    `json:"billing_period"`
	ComputeSeconds int64     `json:"compute_seconds"`
	BandwidthBytes int64     `json:"bandwidth_bytes"`
}

// USAGE (BILLING)
// "Upsert" logic: If the month record exists, add to it. If not, create it.
func (q *Queries) IncrementProjectUsage(ctx context.Context, arg IncrementProjectUsageParams) (ProjectUsage, error) {
	row := q.db.QueryRowContext(ctx, incrementProjectUsage,
		arg.ID,
		arg.ProjectID,
		arg.BillingPeriod,
		arg.ComputeSeconds,
		arg.BandwidthBytes,
	)
	var i ProjectUsage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BillingPeriod,
		&i.ComputeSeconds,
		&i.BandwidthBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentDeployments = `-- name: ListRecentDeployments :many
SELECT id, project_id, image, replicas, status, url, created_at, updated_at FROM deployments
WHERE project_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListRecentDeploymentsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

// Highly optimized: Uses the idx_deployments_project_id_id index to fetch recent deployments instantly
func (q *Queries) ListRecentDeployments(ctx context.Context, arg ListRecentDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeployments, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Image,
			&i.Replicas,
			&i.Status,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjects = `-- name: ListUserProjects :many
SELECT p.id, p.name, p.region, p.created_at, p.updated_at, pm.role
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1
ORDER BY p.id DESC
`

type ListUserProjectsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Region    string    `json:"region"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Role      string    `json:"role"`
}

// Fetch all projects a user has access to, ordered by newest first using UUIDv7
func (q *Queries) ListUserProjects(ctx context.Context, userID uuid.UUID) ([]ListUserProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProjectsRow
	for rows.Next() {
		var i ListUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, image, replicas, status, url, created_at, updated_at
`

type UpdateDeploymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeploymentStatus, arg.ID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Image,
		&i.Replicas,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
