package db

import (
	"database/sql"
	"fmt"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// Store provides all functions to execute db queries and transactions.
// It embeds the sqlc-generated *Queries so you can call queries directly on the Store.
type Store struct {
	*Queries
	db *sql.DB
}

// Connect establishes the connection pool and verifies it is alive.
func Connect(databaseURL string) (*Store, error) {
	if databaseURL == "" {
		// Default local dev string if none provided
		databaseURL = "postgres://platform:secretpassword@localhost:5432/platform_db?sslmode=disable"
	}

	conn, err := sql.Open("pgx", databaseURL)
	if err != nil {
		return nil, fmt.Errorf("failed to open database connection: %w", err)
	}

	// Ping to ensure the database is actually reachable
	if err := conn.Ping(); err != nil {
		return nil, fmt.Errorf("database is unreachable: %w", err)
	}

	return &Store{
		Queries: New(conn), // New() is generated by sqlc
		db:      conn,
	}, nil
}

// Close gracefully shuts down the database connection pool.
func (s *Store) Close() error {
	return s.db.Close()
}
