apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    platform.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    chart: ingress-nginx
    targetRevision: "4.14.3"
    helm:
      parameters:
        - name: controller.service.type
          value: LoadBalancer
        - name: controller.config.use-proxy-protocol
          value: "true"
        - name: controller.service.annotations.kubernetes\\.io/ingress\\.class
          value: nginx
        - name: controller.metrics.enabled
          value: "true"
        - name: controller.podSecurityContext.runAsNonRoot
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
