apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  labels:
    platform.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: "https://fluent.github.io/helm-charts"
    chart: fluent-bit
    targetRevision: "3.0.0"
    helm:
      values: |
        config:
          inputs: |
            [INPUT]
                Name              tail
                Path              /var/log/containers/*.log
                multiline.parser  docker, cri
                Tag               kube.*
                Mem_Buf_Limit     50MB
                Skip_Long_Lines   On
          filters: |
            [FILTER]
                Name                kubernetes
                Match               kube.*
                Kube_URL            https://kubernetes.default.svc:443
                Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
                Merge_Log           On
                Keep_Log            Off
                K8S-Logging.Parser  On
                K8S-Logging.Exclude Off
          outputs: |
            [OUTPUT]
                Name        loki
                Match       kube.*
                Host        loki.observability.svc.cluster.local
                Port        3100
                Labels      job=fluent-bit,namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name']
                Auto_Kubernetes_Labels On
        tolerations:
          - operator: Exists
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
