// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/kendricklawton/project-platform/core/internal/web/ui/components"

func TemplateDetailPage(userName string, slug string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = TemplateDetailContent(userName, slug).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout("Go Portfolio | Templates | Platform", userName).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func TemplateDetailContent(userName string, slug string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col gap-12 py-12\"><a href=\"/templates\" hx-get=\"/templates\" hx-target=\"#main-content\" hx-push-url=\"/templates\" class=\"inline-flex items-center gap-2 text-xs text-zinc-500 dark:text-atom-muted hover:text-zinc-900 dark:hover:text-white transition-colors w-fit\"><i data-lucide=\"arrow-left\" width=\"13\" height=\"13\"></i> Back to Templates</a><section class=\"flex flex-col sm:flex-row sm:items-start sm:justify-between gap-6\"><div class=\"flex flex-col gap-3\"><span class=\"text-[10px] font-mono text-zinc-400 dark:text-atom-muted uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("// template · 01")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 27, Col: 122}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span><h1 class=\"text-3xl sm:text-4xl font-black text-zinc-900 dark:text-white uppercase tracking-tight\">Go Portfolio</h1><p class=\"text-sm text-zinc-500 dark:text-atom-muted max-w-lg leading-relaxed\">Terminal-style personal portfolio for Go developers. Bio, projects, and contact form. Ships as a single static binary — deploy in one command.</p><div class=\"flex items-center gap-2 mt-1\"><span class=\"text-[9px] font-mono font-bold px-2 py-0.5 border border-zinc-300 dark:border-atom-border text-zinc-500 dark:text-atom-muted uppercase tracking-widest\">Go</span> <span class=\"text-[9px] font-mono font-bold px-2 py-0.5 border border-zinc-300 dark:border-atom-border text-zinc-500 dark:text-atom-muted uppercase tracking-widest\">Templ</span> <span class=\"text-[9px] font-mono font-bold px-2 py-0.5 border border-zinc-300 dark:border-atom-border text-zinc-500 dark:text-atom-muted uppercase tracking-widest\">HTMX</span> <span class=\"text-[9px] font-mono font-bold px-2 py-0.5 border border-zinc-300 dark:border-atom-border text-zinc-500 dark:text-atom-muted uppercase tracking-widest\">Tailwind</span></div></div><div class=\"flex items-center gap-3 shrink-0\"><a href=\"https://github.com/kendricklawton/go-portfolio\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"inline-flex items-center gap-2 px-5 py-2.5 border border-zinc-300 dark:border-atom-border text-zinc-700 dark:text-atom-fg text-xs font-bold tracking-widest uppercase hover:border-zinc-900 dark:hover:border-atom-fg hover:text-zinc-900 dark:hover:text-white transition-colors\"><i data-lucide=\"github\" width=\"13\" height=\"13\"></i> View Repo</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if userName != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/dashboard\" class=\"inline-flex items-center gap-2 px-5 py-2.5 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 text-xs font-bold tracking-widest uppercase hover:opacity-90 transition-opacity\"><i data-lucide=\"rocket\" width=\"13\" height=\"13\"></i> Deploy</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a href=\"/auth/login\" class=\"inline-flex items-center gap-2 px-5 py-2.5 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 text-xs font-bold tracking-widest uppercase hover:opacity-90 transition-opacity\"><i data-lucide=\"rocket\" width=\"13\" height=\"13\"></i> Deploy</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></section><section class=\"border border-zinc-200 dark:border-atom-border overflow-hidden\"><div class=\"flex items-center gap-2 px-4 py-2.5 bg-zinc-100 dark:bg-atom-surface border-b border-zinc-200 dark:border-atom-border\"><div class=\"w-2.5 h-2.5 bg-red-400 opacity-70\"></div><div class=\"w-2.5 h-2.5 bg-yellow-400 opacity-70\"></div><div class=\"w-2.5 h-2.5 bg-green-400 opacity-70\"></div><div class=\"ml-3 flex-1 bg-white dark:bg-atom-bg border border-zinc-200 dark:border-atom-border px-3 py-1 text-[10px] font-mono text-zinc-400 dark:text-atom-muted\">https://yourname.projectplatform.dev</div></div><div class=\"bg-zinc-950 min-h-[420px] flex flex-col\"><nav class=\"flex items-center justify-between px-8 py-4 border-b border-zinc-800\"><span class=\"text-sm font-black text-white uppercase tracking-widest font-mono\">dev.name</span><div class=\"flex items-center gap-6\"><span class=\"text-[11px] text-zinc-400 font-mono uppercase tracking-widest\">About</span> <span class=\"text-[11px] text-zinc-400 font-mono uppercase tracking-widest\">Projects</span> <span class=\"text-[11px] text-zinc-400 font-mono uppercase tracking-widest\">Contact</span></div></nav><div class=\"flex flex-col gap-5 px-8 py-12 border-b border-zinc-800\"><span class=\"text-[10px] font-mono text-zinc-500 uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("// hello")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 90, Col: 93}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span><h2 class=\"text-4xl font-black text-white uppercase tracking-tight leading-tight\">Go Developer.<br><span class=\"text-zinc-500\">Systems Thinker.</span></h2><p class=\"text-sm text-zinc-400 font-mono max-w-md leading-relaxed\">Building fast, reliable systems with Go. Open source contributor. Infrastructure nerd.</p><div class=\"flex items-center gap-3 mt-2\"><span class=\"inline-flex items-center gap-2 px-4 py-2 bg-white text-black text-xs font-bold tracking-widest uppercase\">View Projects</span> <span class=\"inline-flex items-center gap-2 px-4 py-2 border border-zinc-700 text-zinc-300 text-xs font-bold tracking-widest uppercase\">GitHub</span></div></div><div class=\"grid grid-cols-3 divide-x divide-zinc-800 border-b border-zinc-800\"><div class=\"p-6 flex flex-col gap-2\"><span class=\"text-[10px] font-mono text-zinc-500 uppercase tracking-widest\">01_</span> <span class=\"text-xs font-bold text-white uppercase tracking-widest\">api-gateway</span> <span class=\"text-[10px] text-zinc-500 font-mono\">Go · REST · eBPF</span></div><div class=\"p-6 flex flex-col gap-2\"><span class=\"text-[10px] font-mono text-zinc-500 uppercase tracking-widest\">02_</span> <span class=\"text-xs font-bold text-white uppercase tracking-widest\">worker-pool</span> <span class=\"text-[10px] text-zinc-500 font-mono\">Go · concurrency</span></div><div class=\"p-6 flex flex-col gap-2\"><span class=\"text-[10px] font-mono text-zinc-500 uppercase tracking-widest\">03_</span> <span class=\"text-xs font-bold text-white uppercase tracking-widest\">cli-toolkit</span> <span class=\"text-[10px] text-zinc-500 font-mono\">Go · Cobra · TUI</span></div></div></div></section><section class=\"grid md:grid-cols-3 gap-12\"><div class=\"md:col-span-2 flex flex-col gap-8\"><div class=\"flex flex-col gap-4\"><span class=\"text-[10px] font-mono text-zinc-400 dark:text-atom-muted uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs("// about")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 125, Col: 114}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span><p class=\"text-sm text-zinc-600 dark:text-atom-muted leading-relaxed\">A production-ready personal portfolio built for Go developers who want full control. No JavaScript frameworks — just Go, Templ, HTMX, and Tailwind. The entire site compiles to a single static binary under 10 MB.</p><p class=\"text-sm text-zinc-600 dark:text-atom-muted leading-relaxed\">Includes a contact form with server-side validation, project cards pulled from a simple Go slice, dark mode, and responsive layout. Swap in your own content and deploy.</p></div><div class=\"flex flex-col gap-4\"><span class=\"text-[10px] font-mono text-zinc-400 dark:text-atom-muted uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs("// getting-started")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 131, Col: 124}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span><div class=\"flex flex-col gap-px border border-zinc-200 dark:border-atom-border\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStep("01", "Clone the repo", "git clone https://github.com/kendricklawton/go-portfolio").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStep("02", "Install dependencies", "go mod download").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStep("03", "Build the binary", "go build -o portfolio ./cmd/portfolio").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStep("04", "Deploy to Platform", "plat deploy").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></div></div><div class=\"flex flex-col gap-6\"><div class=\"border border-zinc-200 dark:border-atom-border p-5 flex flex-col gap-4\"><span class=\"text-[10px] font-mono text-zinc-400 dark:text-atom-muted uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs("// repository")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 143, Col: 119}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span> <a href=\"https://github.com/kendricklawton/go-portfolio\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"flex items-center gap-2 text-xs text-zinc-700 dark:text-atom-fg hover:text-zinc-900 dark:hover:text-white transition-colors\"><i data-lucide=\"github\" width=\"14\" height=\"14\"></i> kendricklawton/go-portfolio</a></div><div class=\"border border-zinc-200 dark:border-atom-border p-5 flex flex-col gap-4\"><span class=\"text-[10px] font-mono text-zinc-400 dark:text-atom-muted uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs("// stack")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 155, Col: 114}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</span><ul class=\"flex flex-col gap-2.5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStackItem("Go 1.23+", "Runtime").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStackItem("Templ", "HTML templating").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStackItem("HTMX", "Partial swaps").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStackItem("Tailwind CSS v4", "Styling").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templateStackItem("Air", "Hot reload (dev)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</ul></div><div class=\"border border-zinc-200 dark:border-atom-border p-5 flex flex-col gap-4\"><span class=\"text-[10px] font-mono text-zinc-400 dark:text-atom-muted uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs("// plan")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 165, Col: 113}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</span><div class=\"flex items-center gap-2\"><span class=\"text-[9px] font-mono font-bold px-2 py-0.5 border border-atom-green/40 text-atom-green uppercase tracking-widest\">Free</span> <span class=\"text-xs text-zinc-500 dark:text-atom-muted\">Available on all plans</span></div></div></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func templateStep(num string, title string, cmd string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var11 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var11 == nil {
			templ_7745c5c3_Var11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"bg-white dark:bg-atom-bg p-4 flex flex-col gap-2 border-b border-zinc-200 dark:border-atom-border last:border-b-0\"><div class=\"flex items-center gap-3\"><span class=\"text-[10px] font-mono text-zinc-400 dark:text-atom-muted uppercase tracking-widest shrink-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(num)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 179, Col: 114}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</span> <span class=\"text-xs font-bold text-zinc-900 dark:text-white uppercase tracking-widest\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 string
		templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 180, Col: 98}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</span></div><div class=\"ml-8 bg-zinc-950 dark:bg-atom-border px-3 py-2\"><code class=\"text-[11px] font-mono text-atom-green\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 string
		templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(cmd)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 183, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</code></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func templateStackItem(name string, role string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var15 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var15 == nil {
			templ_7745c5c3_Var15 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<li class=\"flex items-center justify-between\"><span class=\"text-xs font-bold text-zinc-900 dark:text-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 190, Col: 70}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</span> <span class=\"text-[11px] text-zinc-400 dark:text-atom-muted font-mono\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(role)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/pages/template_detail.templ`, Line: 191, Col: 79}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</span></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
